#! /bin/sh

R=$1;
C=$2;
folder=/opt/Mazemaker/mazemaker_support;
currentDir=`pwd`;

clean(){
	echo rm -f maze*.png;
	rm -f maze*.png;
}

make(){
	$folder/mazemake ${R:=60} ${C:=80} > maze.txt;
	$folder/mazesolve < maze.txt > path.txt;

	mazename="maze_${R}x${C}.png";
	pathname="maze_path_${R}x${C}.png";


	$folder/mazeshow 10 maze.txt | convert - $mazename;
	$folder/mazeshow 10 maze.txt path.txt | convert - $pathname;

	rm maze.txt path.txt;
}




if [ $R ] && [ $R = "clean" ]; then # make sure variable is not empty
	clean;
else
	make;
fi;
